import T from 'prop-types'

export const ProposalPropTypes = T.shape({
  accepted: T.string,
  allVotes: T.number,
  address: T.string,
  checkedTimes: T.number,
  code: T.string,
  codeName: T.string,
  compareErrors: T.string,
  description: T.string,
  emergency: T.string,
  endBlock: T.string,
  hardCapReached: T.string,
  key: T.string,
  lastCheckedBlock: T.string,
  leading: T.bool,
  location: T.string,
  myAccepts: T.string,
  myRefuses: T.string,
  myVotes: T.number,
  refused: T.string,
  replaces: T.string,
  replacesCode: T.string,
  result: T.bool,
  resultBlock: T.string,
  surveyEnd: T.bool,
  terminated: T.string,
  terminationData: T.string,
  withdrawed: T.string,
}).isRequired
